### ISSUE TITLE
Add out-of-the-box support for PostCSS

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-themes-sdk#46]
From [use autoprefixer for css and sass](https://github.com/liferay/liferay-theme-tasks/issues/81) by @marcelmokos and [Apply postcss during build of a Liferay 7 theme](https://github.com/liferay/liferay-theme-tasks/issues/70) by @caneta

References on current approach:
- [styled-svg-sprite-theme](https://github.com/marcoscv-work/styled-svg-sprite-theme)
- [styled-postcss-theme](https://github.com/marcoscv-work/styled-postcss-theme)

**Comment by yuchi** [comment]
By the way you can already add Autoprefixer support with [an hook we made at @smclab](https://github.com/smclab/liferay-theme-hooks).

**Comment by jbalsas** [comment]
Thanks for the reference, @yuchi! Added this to the list on top! 👏

**Comment by sbaechler** [comment]
@yuchi You should remove the existing prefixes first with [unprefix](https://www.npmjs.com/package/postcss-unprefix).

**Comment by sbaechler** [comment]
#83 is preventing PostCSS from generating Sourcemaps.

**Comment by yuchi** [comment]
@sbaechler That’s a very nice suggestion. I created an issue to track it down.

PS: If you could use those hooks we would be very happy to have some feedback.

PPS: You gained a follower given your last weeks of issue contributing here :) Will you be at DEVCON this year?

**Comment by sbaechler** [comment]
@yuchi I created my own hooks before I saw yours.

Those are mine:
```
const postcssPlugins = [
    unprefix(),
    flexbugFixes(),
    autoprefixer({
        flexbox: 'no-2009',
    }),
];

// This is called from within hookFn
function themeTasks({gulp, pathSrc, pathBuild}) { 
    gulp.task('build:postcss', function(done) {
        const base = path.join(pathBuild, '_css');
        gulp
           .src(path.join(base, '*.css'), {
               base,
           })
           .pipe(sourcemaps.init({ loadMaps: false, largeFile: true }))
           .pipe(postcss(postcssPlugins))
           .pipe(sourcemaps.write('.'))
           .pipe(gulp.dest(path.join(pathBuild, '_postcss')))
           .on('end', done);
    });

    gulp.task('build:move-compiled-css', function() {
        return gulp
            .src(pathBuild + '/_postcss/**/*')
            .pipe(gulp.dest(pathBuild + '/css'));
    });

    gulp.task('build:remove-old-css-dir', function(cb) {
        del([pathBuild + '/_css']);
        del([pathBuild + '/_postcss'], cb);
    });
}
```
I am using another temporary build folder since I had problems using the same folder as source and dest.

I think it would be quite easy to add PostCSS to the liferay-theme-tasks. This would also allow the developers to customise `browserslist` per their requirements.

Of course `unprefix` is only used to remove the Liferay and Clay CSS prefixes. If Liferay added PostCSS, they could just run this over their codebase once.

PPS: Sorry, currently I cannot attend any conferences.

**Comment by protoEvangelion** [comment]
@jbalsas How do we pass options to autoprefixer? It doesn't seem like the code allows for this.

```javascript
autoprefixer({
  browsers: ['last 2 versions'],
  cascade: false
})
```

**Comment by sbaechler** [comment]
@protoEvangelion 
True, it is not possible to configure autoprefixer this way.
But autoprefixer should take the browsers defined in `browserslist` in the package.json of your app.

**Comment by protoEvangelion** [comment]
@sbaechler will it do that automatically now?

**Comment by jbalsas** [comment]
Hey @protoEvangelion, as @sbaechler mentions, the [recommended way](https://github.com/postcss/autoprefixer#browsers) to configure browsers is through the `browserslist` key in your `package.json`.

I just created a new theme using the `rc.1` version of the `generator-liferay-theme` and added this to my `package.json`:

```json
{
    "browserslist": ["last 4 version"],
    ...      
    "liferayTheme": {
        "baseTheme": "styled",
        "postcss": [
            "autoprefixer"
        ],
        "screenshot": "",
        "rubySass": false,
        "templateLanguage": "ftl",
        "version": "7.1"
    },
    ...
}
```

I can assert that this successfully gets processed by `autoprefixer`:

```css
/* _custom.scss */
.example {
    display: grid;
    transition: all .5s;
    user-select: none;
    background: linear-gradient(to bottom, white, black);
}

/* main.css */
.example {
  display: grid;
  -webkit-transition: all .5s;
  -o-transition: all .5s;
  transition: all .5s;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
  background: -webkit-gradient(linear, left top, left bottom, from(white), to(black));
  background: -webkit-linear-gradient(top, white, black);
  background: -o-linear-gradient(top, white, black);
  background: linear-gradient(to bottom, white, black); }
```

As for other options, the current logic [only accepts a list of plugin names](https://github.com/liferay/liferay-themes-sdk/blob/master/packages/liferay-theme-tasks/tasks/build/compile-css.js#L132-L141). 

I've created https://github.com/liferay/liferay-themes-sdk/issues/126 to make this possible. Would you mind chiming in there to see if that would address your issue?

Thanks!
